# IMDB Movie Data Cleaning and Analysis

In [153]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [154]:
df = pd.read_csv("data/messy_IMDB_dataset.csv", sep=";", encoding='latin-1')
df.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

In [155]:
df.shape

(101, 12)

In [156]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IMBD title ID   100 non-null    str
 1   Original titlÊ  100 non-null    str
 2   Release year    100 non-null    str
 3   Genrë¨          100 non-null    str
 4   Duration        99 non-null     str
 5   Country         100 non-null    str
 6   Content Rating  77 non-null     str
 7   Director        100 non-null    str
 8   Unnamed: 8      0 non-null      float64
 9   Income          100 non-null    str
 10   Votes          100 non-null    str
 11  Score           100 non-null    str
dtypes: float64(1), str(11)
memory usage: 9.6 KB

In [157]:
df.sample(5)

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
34,tt0088763,Back to the Future,1985-10-18,"Adventure, Comedy, Sci-Fi",116,USA,PG,Robert Zemeckis,NaN,$ 388774684,1.027.330,8.5
63,tt2380307,Coco,2017-12-28,"Animation, Adventure, Family",105,USA,NaN,"Lee Unkrich, Adrian Molina",NaN,$ 807083670,352.455,8.1
45,tt0034583,Casablanca,21-11-46,"Drama, Romance, War",102,USA,PG,Michael Curtiz,NaN,$ 4374761,509.953,8.3
84,tt0075314,Taxi Driver,1976-13-24,"Crime, Drama",114,USA,R,Martin Scorsese,NaN,$ 28441292,703.264,7.7
66,tt1187043,3 Idiots,2009-12-25,"Comedy, Drama",170,India,NaN,Rajkumar Hirani,NaN,$ 60262836,332.217,8.1

## Damage Report - messy_IMDB_dataset.csv

**File Level**
- Values are semicolon-seperated despite its .csv extension
- Not UTF-8 characters are littered in cells
- Column names filled with inconsistent encoding
- Some numbers contain letters

**Nulls**
- A null column is present in the middle
- Completely empty row(s)
- Duration and Content Rating have missing values
- Alternate names for what should be null values

**Column: Release Year**
- Values are in type str instead of datetime
- Some dates are in words rather than numbers
- Some numbered dates are formatted shorter i.e 1946 -> 46
- Date formatting is inconsistent i.e year first or year last

**Column: Country**
- Some typos in country spellings

**Column: Income**
- Are of type str instead of Int
- Some incomes are unreasonably small

**Column: Votes**
- str type instead of int
- Values formatted with . every three zeros instead of ,

**Column: Score**
- str instead of float
- Inconsistent, garbage punctuation

**Column: Genre**
- Multiple value column

In [158]:
df.columns
print(df['Unnamed: 8'].isna().all())
df.drop(columns='Unnamed: 8', inplace=True)

True

In [159]:
mask = df.isna().all(axis=1)
df[mask]

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Income,Votes,Score
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [160]:
df.dropna(how ='all', inplace=True)

In [161]:
df.columns = ['title_id', 'original_title', 'release_year', 'genre', 'duration', 'country', 'content_rating', 'director','income','votes','score']
df

,title_id,original_title,release_year,genre,duration,country,content_rating,director,income,votes,score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,$ 222831817,1.780.147,"8,9f"
...,...,...,...,...,...,...,...,...,...,...,...
96,tt0070735,The Sting,1974-03-21,"Comedy, Crime, Drama",129,USA,PG,George Roy Hill,$ 156000000,236.285,7.5
97,tt0082096,Das Boot,1982-03-18,"Adventure, Drama, Thriller",149,West Germany,R,Wolfgang Petersen,$ 11487676,226.427,7.5
98,tt0059578,Per qualche dollaro in piÃ¹,1965-12-20,Western,132,Italy,NaN,Sergio Leone,$ 15000000,226.039,7.4
99,tt1832382,Jodaeiye Nader az Simin,2011-10-21,Drama,123,Iran,PG-13,Asghar Farhadi,$ 22926076,214.165,7.4
100,tt0045152,Singin' in the Rain,1953-02-05,"Comedy, Musical, Romance",103,USA,NaN,Stanley Donen,$ 1864182,213.152,7.4

In [162]:
df.duplicated().sum()

np.int64(0)

**Initial Cleaning**
- Unnamed/Empty Column and Row dropped
- Renamed the column names to clean appropriate snake-case versions
- No duplicates found so none dropped

In [163]:
df['country'].value_counts()

country
USA             62
UK              12
Italy            4
Japan            4
France           3
South Korea      2
Germany          2
US               1
New Zealand      1
New Zesland      1
New Zeland       1
US.              1
Brazil           1
Italy1           1
India            1
Denmark          1
West Germany     1
Iran             1
Name: count, dtype: int64

In [164]:
country_fix = {'New Zesland': 'New Zealand', 'New Zeland':'New Zealand', 'US.':'USA', 'US':'USA', 'Italy1':'Italy', 'West Germany':'Germany'}
df['country'] = df['country'].replace(country_fix)

In [165]:
df['country'].value_counts()

country
USA            64
UK             12
Italy           5
Japan           4
New Zealand     3
France          3
Germany         3
South Korea     2
Brazil          1
India           1
Denmark         1
Iran            1
Name: count, dtype: int64

In [166]:
df['duration'] = df['duration'].str.replace(r"[^0-9]", "", regex=True)
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')
df['duration'] = df['duration'].fillna(df['duration'].median())

In [167]:
df['duration'].describe()

count    100.000000
mean     135.000000
std       30.399445
min       81.000000
25%      115.000000
50%      129.500000
75%      150.250000
max      229.000000
Name: duration, dtype: float64

**Country and Duration**
- Country misspellings fixed but ensuring each country has one correct spelling
- Null/Garbage values removed from duration and replaced by the median

In [168]:
df['content_rating'].unique()

<StringArray>
['R', 'PG-13', 'Not Rated', 'Approved', 'PG', nan, 'Unrated', 'G']
Length: 8, dtype: str

In [169]:
ratings = {'Not Rated':'Unrated'}
df['content_rating'] = df['content_rating'].replace(ratings)

In [170]:
df['content_rating'].unique()

<StringArray>
['R', 'PG-13', 'Unrated', 'Approved', 'PG', nan, 'G']
Length: 7, dtype: str

In [171]:
df['content_rating'] = df['content_rating'].fillna('Unknown')

In [172]:
df['content_rating'].value_counts(dropna=False)

content_rating
R           45
Unknown     23
PG-13       12
PG          11
G            6
Unrated      2
Approved     1
Name: count, dtype: int64

**Content Rating**
- Not Rated and Unrated combined into a single category Unrated
- Approved kept as a historical category
- All empty ratings

In [173]:
df['income'] = df['income'].str.replace('o','0')
df['income'] = df['income'].str.replace(r"[^0-9]","", regex=True)
df['income'] = pd.to_numeric(df['income'], errors = 'coerce')
df.loc[df['original_title'] == '12 Angry Men', 'income'] = 2877755

In [174]:
df.head()
df.info()

<class 'pandas.DataFrame'>
Index: 100 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title_id        100 non-null    str
 1   original_title  100 non-null    str
 2   release_year    100 non-null    str
 3   genre           100 non-null    str
 4   duration        100 non-null    float64
 5   country         100 non-null    str
 6   content_rating  100 non-null    str
 7   director        100 non-null    str
 8   income          100 non-null    int64
 9   votes           100 non-null    str
 10  score           100 non-null    str
dtypes: float64(1), int64(1), str(9)
memory usage: 9.4 KB

**Income**
- Dollar signs removed
- Typos of 0 as o fixed
- Column converted to integer

In [175]:
df['votes'] = df['votes'].str.replace('.','')
df['votes'] = pd.to_numeric(df['votes'], errors='coerce')
df['votes']

0      2278845
1      1572674
2      2241615
3      1098714
4      1780147
        ...
96      236285
97      226427
98      226039
99      214165
100     213152
Name: votes, Length: 100, dtype: int64

In [176]:
df['score'] = df['score'].replace(r"[,:]", '.', regex=True)
df['score'] = df['score'].replace(r"[^0-9^\.]", "", regex=True)
df['score'] = df['score'].replace(r"\.\.", '.', regex=True)
df['score']= pd.to_numeric(df['score'], errors='coerce')
df['score'] = df['score'].fillna(df['score'].median())
df['score'].value_counts()

score
8.6    12
8.3     9
8.2     8
8.4     7
8.1     7
8.5     6
8.0     6
7.8     6
7.5     6
8.8     5
7.9     5
8.9     4
8.7     4
7.7     4
7.6     4
7.4     3
9.0     2
9.3     1
9.2     1
Name: count, dtype: int64

**Score**
- All non decimal punctuation and repeated decimals replaced with single decimals
- All non numeric characters removed
- Column converted to floats and null value replaced with the median of the column

In [177]:
df['release_year'].unique()
parsed = pd.to_datetime(df['release_year'], errors = 'coerce', format='mixed')
df[parsed.isna()]['release_year']

70    The 6th of marzo, year 1951
83                     1984-02-34
84                     1976-13-24
Name: release_year, dtype: str

In [178]:
df[parsed.isna()]['original_title']

70    Sunset Blvd.
83        Scarface
84     Taxi Driver
Name: original_title, dtype: str

In [179]:
df.loc[df['original_title']== 'Sunset Blvd.', 'release_year'] = '06-03-1951'
df.loc[df['original_title']== 'Scarface', 'release_year'] = '01-01-1984'
df.loc[df['original_title']== 'Taxi Driver', 'release_year'] = '01-01-1976'
df['release_year'] = pd.to_datetime(df['release_year'], errors = 'coerce', format='mixed')
check = df['release_year'].dt.year.between(1920,2024)
df[~check]

,title_id,original_title,release_year,genre,duration,country,content_rating,director,income,votes,score
45,tt0034583,Casablanca,2046-11-21,"Drama, Romance, War",102.0,USA,PG,Michael Curtiz,4374761,509953,8.3

In [180]:
df.loc[df['original_title'] == 'Casablanca', 'release_year'] = '23-11-1942'

In [181]:
df['year'] = df['release_year'].dt.year

**Release Year**
- All string dates are now in a datetime format
- Invalid dates were fixed manually 
- Out of bound date found which was fixed by looking up the correct date on IMDB

In [193]:
assert df['country'].nunique() == 12, "Invalid/Typo Country Names Present"
assert df['duration'].all() > 0, "Negative duration Values Present"
assert df['duration'].between(10,300).all(), 'Non Plausible Duration Values'
assert df['content_rating'].nunique() == 7, "Invalid Ratings Present"
assert df.shape[0] == 100, "Row count is invalid"
assert df['country'].notna().all() == True, "Null Values"
assert df['duration'].notna().all() == True, "Null Values"
assert df['content_rating'].notna().all() == True, "Null Values"
assert df['original_title'].notna().all() == True, "Null Values"
assert df['release_year'].notna().all() == True, "Null Values"
assert df['genre'].notna().all() == True, "Null Values"
assert df['director'].notna().all() == True, "Null Values"
assert df['income'].notna().all() == True, "Null Values"
assert df['votes'].notna().all() == True, "Null Values"
assert df['score'].notna().all() == True, "Null Values"
assert df['duration'].dtype == 'float64', "Duration is not float"
assert df['income'].dtype == 'int64', "Income is not integer"
assert df['votes'].dtype == 'int64', "Votes is not integer"
assert df['score'].dtype == 'float64', "Score is not float"

In [196]:
df = df.drop(columns='release_year')
df.to_csv('data/clean_imdb.csv', index=False)

**Validation**
- Use of asserts to validate the dataframe and ensure all columns are in the form that we require
- Cleaned csv is saved to data